apiVersion: v1
kind: Service
metadata:
  name: cakephp3
spec:
  type: LoadBalancer
  loadBalancerIP: ${LOAD_BALANCER}
  selector:
    app: cakephp3-prod
  ports:
    - name: cakephp3
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
status:
  loadBalancer:
    ingress:
    - ip: ${LOAD_BALANCER}